import { createTheme } from "@mui/material";

const customTheme = createTheme({
    colorSchemes: { light: true, dark: true },
    cssVariables: {
        colorSchemeSelector: 'class',
        body: {
            background:' #f5e4e8',
            background: 'radial-gradient(circle, #f5e4e8 24%, #e0eaff 100%)',
        }
    },
    breakpoints: {
        values: {
            xs: 0,
            sm: 600,
            md: 900,
            lg: 1200,
            xl: 1536,
        },
    },
    typography: {
        h2: {fontFamily: 'playfair display'},
        h3: {fontFamily: 'playfair display'},
        h4: {fontFamily: 'playfair display'},
        h5: {fontFamily: 'montserrat'},
        p: {fontFamily: 'montserrat'},
        body: {fontFamily: 'montserrat'},
        span: {fontFamily: 'montserrat'},
        caption: {fontFamily: 'montserrat'},        
        body1: {fontFamily: 'montserrat'},          
        body2: {fontFamily: 'montserrat'},          
        subtitle1: {fontFamily: 'montserrat'},      
        subtitle2: {fontFamily: 'montserrat'},     
    },
    palette: {
        description: "TYPE: CUSTOM\nMaterial Theme Builder export 2025-06-12 08:52:53",
        seed: "#ABC6FE",
        coreColors: {
            primary: "#ABC6FE"
        },
        extendedColors: [],
        schemes: {
            light: {
                primary: "#435E90",
                surfaceTint: "#435E90",
                onPrimary: "#FFFFFF",
                primaryContainer: "#ABC6FE",
                onPrimaryContainer: "#365282",
                secondary: "#555E74",
                onSecondary: "#FFFFFF",
                secondaryContainer: "#D9E2FC",
                onSecondaryContainer: "#5B647A",
                tertiary: "#7B4E7F",
                onTertiary: "#FFFFFF",
                tertiaryContainer: "#EAB4EB",
                onTertiaryContainer: "#6D4271",
                error: "#BA1A1A",
                onError: "#FFFFFF",
                errorContainer: "#FFDAD6",
                onErrorContainer: "#93000A",
                background: "#FAF9FD",
                onBackground: "#1A1B1F",
                surface: "#FAF9FD",
                onSurface: "#1A1B1F",
                surfaceVariant: "#E0E2EC",
                onSurfaceVariant: "#44474F",
                outline: "#747780",
                outlineVariant: "#C4C6D0",
                shadow: "#000000",
                scrim: "#000000",
                inverseSurface: "#2F3034",
                inverseOnSurface: "#F1F0F5",
                inversePrimary: "#ACC7FF",
                primaryFixed: "#D7E2FF",
                onPrimaryFixed: "#001A40",
                primaryFixedDim: "#ACC7FF",
                onPrimaryFixedVariant: "#2A4676",
                secondaryFixed: "#D9E2FC",
                onSecondaryFixed: "#121C2E",
                secondaryFixedDim: "#BDC6DF",
                onSecondaryFixedVariant: "#3D475B",
                tertiaryFixed: "#FFD6FD",
                onTertiaryFixed: "#310937",
                tertiaryFixedDim: "#EBB5EC",
                onTertiaryFixedVariant: "#613765",
                surfaceDim: "#DAD9DE",
                surfaceBright: "#FAF9FD",
                surfaceContainerLowest: "#FFFFFF",
                surfaceContainerLow: "#F4F3F8",
                surfaceContainer: "#EEEDF2",
                surfaceContainerHigh: "#E9E7EC",
                surfaceContainerHighest: "#E3E2E6"
            },
            lightMediumContrast: {
                primary: "#173565",
                surfaceTint: "#435E90",
                onPrimary: "#FFFFFF",
                primaryContainer: "#526D9F",
                onPrimaryContainer: "#FFFFFF",
                secondary: "#2D364A",
                onSecondary: "#FFFFFF",
                secondaryContainer: "#636D83",
                onSecondaryContainer: "#FFFFFF",
                tertiary: "#4F2654",
                onTertiary: "#FFFFFF",
                tertiaryContainer: "#8B5D8E",
                onTertiaryContainer: "#FFFFFF",
                error: "#740006",
                onError: "#FFFFFF",
                errorContainer: "#CF2C27",
                onErrorContainer: "#FFFFFF",
                background: "#FAF9FD",
                onBackground: "#1A1B1F",
                surface: "#FAF9FD",
                onSurface: "#101114",
                surfaceVariant: "#E0E2EC",
                onSurfaceVariant: "#33363E",
                outline: "#4F525B",
                outlineVariant: "#6A6D76",
                shadow: "#000000",
                scrim: "#000000",
                inverseSurface: "#2F3034",
                inverseOnSurface: "#F1F0F5",
                inversePrimary: "#ACC7FF",
                primaryFixed: "#526D9F",
                onPrimaryFixed: "#FFFFFF",
                primaryFixedDim: "#395585",
                onPrimaryFixedVariant: "#FFFFFF",
                secondaryFixed: "#636D83",
                onSecondaryFixed: "#FFFFFF",
                secondaryFixedDim: "#4B556A",
                onSecondaryFixedVariant: "#FFFFFF",
                tertiaryFixed: "#8B5D8E",
                onTertiaryFixed: "#FFFFFF",
                tertiaryFixedDim: "#714574",
                onTertiaryFixedVariant: "#FFFFFF",
                surfaceDim: "#C7C6CA",
                surfaceBright: "#FAF9FD",
                surfaceContainerLowest: "#FFFFFF",
                surfaceContainerLow: "#F4F3F8",
                surfaceContainer: "#E9E7EC",
                surfaceContainerHigh: "#DDDCE1",
                surfaceContainerHighest: "#D2D1D6"
            },
            dark: {
                primary: "#D6E2FF",
                surfaceTint: "#ACC7FF",
                onPrimary: "#0F2F5E",
                primaryContainer: "#ABC6FE",
                onPrimaryContainer: "#365282",
                secondary: "#BDC6DF",
                onSecondary: "#273044",
                secondaryContainer: "#3D475B",
                onSecondaryContainer: "#ABB5CD",
                tertiary: "#FFD4FE",
                onTertiary: "#48204D",
                tertiaryContainer: "#EAB4EB",
                onTertiaryContainer: "#6D4271",
                error: "#FFB4AB",
                onError: "#690005",
                errorContainer: "#93000A",
                onErrorContainer: "#FFDAD6",
                background: "#121317",
                onBackground: "#E3E2E6",
                surface: "#121317",
                onSurface: "#E3E2E6",
                surfaceVariant: "#44474F",
                onSurfaceVariant: "#C4C6D0",
                outline: "#8E909A",
                outlineVariant: "#44474F",
                shadow: "#000000",
                scrim: "#000000",
                inverseSurface: "#E3E2E6",
                inverseOnSurface: "#2F3034",
                inversePrimary: "#435E90",
                primaryFixed: "#D7E2FF",
                onPrimaryFixed: "#001A40",
                primaryFixedDim: "#ACC7FF",
                onPrimaryFixedVariant: "#2A4676",
                secondaryFixed: "#D9E2FC",
                onSecondaryFixed: "#121C2E",
                secondaryFixedDim: "#BDC6DF",
                onSecondaryFixedVariant: "#3D475B",
                tertiaryFixed: "#FFD6FD",
                onTertiaryFixed: "#310937",
                tertiaryFixedDim: "#EBB5EC",
                onTertiaryFixedVariant: "#613765",
                surfaceDim: "#121317",
                surfaceBright: "#38393D",
                surfaceContainerLowest: "#0D0E11",
                surfaceContainerLow: "#1A1B1F",
                surfaceContainer: "#1E1F23",
                surfaceContainerHigh: "#292A2D",
                surfaceContainerHighest: "#343538"
            },
        },
        palettes: {
            primary: {
                0: "#000000",
                5: "#00102C",
                10: "#001A40",
                15: "#002453",
                20: "#0F2F5E",
                25: "#1D3B6A",
                30: "#2A4676",
                35: "#375283",
                40: "#435E90",
                50: "#5C77AA",
                60: "#7691C6",
                70: "#91ABE2",
                80: "#ACC7FF",
                90: "#D7E2FF",
                95: "#EDF0FF",
                98: "#F9F9FF",
                99: "#FDFBFF",
                100: "#FFFFFF"
            },
            secondary: {
                0: "#000000",
                5: "#0C111C",
                10: "#161C27",
                15: "#202631",
                20: "#2B303C",
                25: "#363B47",
                30: "#414753",
                35: "#4D525F",
                40: "#595E6B",
                50: "#727785",
                60: "#8C909F",
                70: "#A6ABBA",
                80: "#C1C6D5",
                90: "#DEE2F2",
                95: "#EDF0FF",
                98: "#F9F9FF",
                99: "#FDFBFF",
                100: "#FFFFFF"
            },
            tertiary: {
                0: "#000000",
                5: "#1A0B1D",
                10: "#251628",
                15: "#302033",
                20: "#3B2B3E",
                25: "#473549",
                30: "#534155",
                35: "#5F4C61",
                40: "#6C586D",
                50: "#857087",
                60: "#A08AA1",
                70: "#BBA4BC",
                80: "#D8BFD8",
                90: "#F5DBF4",
                95: "#FFEBFD",
                98: "#FFF7FB",
                99: "#FFFBFF",
                100: "#FFFFFF"
            },
            neutral: {
                0: "#000000",
                5: "#101113",
                10: "#1B1B1E",
                15: "#252628",
                20: "#303032",
                25: "#3B3B3D",
                30: "#464649",
                35: "#525254",
                40: "#5E5E60",
                50: "#777779",
                60: "#919093",
                70: "#ACABAD",
                80: "#C8C6C8",
                90: "#E4E2E4",
                95: "#F2F0F3",
                98: "#FBF8FB",
                99: "#FEFBFE",
                100: "#FFFFFF"
            },
        }

    }
    }
)

export default customTheme